name: flutter_learn
description: A project to learn Flutter.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  badges: ^1.1.1
  battery: ^1.0.1
  camera: ^0.5.8+2
  cached_network_image: ^2.2.0+1
  city_pickers: ^0.1.30
  cupertino_icons: ^0.1.2
  cookie_jar: ^1.0.1
  date_format: ^1.0.8
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  device_info: ^0.4.2+4
  event_bus: ^1.1.1
  extended_image: ^0.9.0
  fluttertoast: ^7.1.6
  flutter_app_badger: ^1.1.2
  flutter_bugly: ^0.2.8
  flutter_colorpicker: ^0.3.4
  flutter_datetime_picker: ^1.4.0
  flutter_downloader: ^1.4.4
  flutter_easyrefresh: ^2.1.1
  flutter_webview_plugin: ^0.3.11
  flutter_spinkit: ^4.1.2+1
  flutter_swiper: ^1.1.6
  flutter_xupdate: ^1.0.2
  flutter_picker: ^1.1.5
  flutter_local_notifications: ^1.4.4+1
  fluro: ^1.7.8
  intl: ^0.16.0
  image_picker: ^0.6.7+14
  image_picker_saver: ^0.3.0
  jpush_flutter: ^0.6.3
  multi_image_picker: ^4.6.7
  oktoast: ^2.3.2
  package_info: ^0.4.1
  path_provider: ^1.6.10
  permission_handler: ^5.0.1
  progress_dialog: ^1.2.4
  provider: ^4.1.3
  qr_code_scanner: ^0.3.4
  shared_preferences: ^0.5.7+3
  share: ^0.6.4+3
  sqflite: ^1.3.1
  url_launcher: ^5.4.10
  umeng_analytics_plugin: ^1.0.3
  video_player: ^0.10.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.9


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/json/
  - assets/app.db

  fonts:
    - family: xuifont  #指定一个字体名
      fonts:
        - asset: assets/fonts/iconfont.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
